// <auto-generated />
using System;
using LojaSonhoDeCafe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaSonhoDeCafe.Migrations.BancoDeDadosMigrations
{
    [DbContext(typeof(BancoDeDados))]
    [Migration("20240417225055_AdicionandoDB")]
    partial class AdicionandoDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carrinhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UsuarioId = "1"
                        },
                        new
                        {
                            Id = 2,
                            UsuarioId = "2"
                        });
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.CarrinhoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CarrinhoItens");
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconeCss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconeCss = "fa-coffee",
                            Nome = "Cafés"
                        },
                        new
                        {
                            Id = 2,
                            IconeCss = "fa-cookie",
                            Nome = "Salgados"
                        },
                        new
                        {
                            Id = 3,
                            IconeCss = "fa-birthday-cake",
                            Nome = "Doces"
                        },
                        new
                        {
                            Id = 4,
                            IconeCss = "fa-hamburger",
                            Nome = "Lanches"
                        });
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("QuantidadeEmEstoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34fdf30d-1a0d-4597-b667-52625d6b70a4"),
                            CategoriaId = 1,
                            Descricao = "Café forte e encorpado, ideal para quem gosta de um sabor intenso.",
                            FotoUrl = "/Imagens/Cafes/espresso.jpg",
                            Nome = "Café Espresso",
                            Preco = 3.50m,
                            QuantidadeEmEstoque = 100
                        },
                        new
                        {
                            Id = new Guid("db2bda1e-492c-4ad9-a5c9-03a2d1eca78b"),
                            CategoriaId = 1,
                            Descricao = "Café suave e cremoso, feito com leite vaporizado.",
                            FotoUrl = "/Imagens/Cafes/latte.jpg",
                            Nome = "Café Latte",
                            Preco = 4.00m,
                            QuantidadeEmEstoque = 80
                        },
                        new
                        {
                            Id = new Guid("3323d5d3-c06a-4ed7-8e2e-992ee7ef8790"),
                            CategoriaId = 1,
                            Descricao = "Café cremoso com uma generosa camada de espuma de leite e canela por cima.",
                            FotoUrl = "/Imagens/Cafes/capuccino.jpg",
                            Nome = "Café Capuccino",
                            Preco = 4.50m,
                            QuantidadeEmEstoque = 70
                        },
                        new
                        {
                            Id = new Guid("792d7b55-f575-4cd6-a601-39f293472c03"),
                            CategoriaId = 2,
                            Descricao = "Croissant recheado com queijo derretido.",
                            FotoUrl = "/Imagens/Salgados/croissant_queijo.jpg",
                            Nome = "Croissant de Queijo",
                            Preco = 5.00m,
                            QuantidadeEmEstoque = 60
                        },
                        new
                        {
                            Id = new Guid("7955c423-3c43-4467-aabc-82de749ea274"),
                            CategoriaId = 2,
                            Descricao = "Pão de queijo quentinho e delicioso.",
                            FotoUrl = "/Imagens/Salgados/pao_queijo.jpg",
                            Nome = "Pão de Queijo",
                            Preco = 3.00m,
                            QuantidadeEmEstoque = 70
                        },
                        new
                        {
                            Id = new Guid("58e04c01-380d-475b-af2e-8edb34d4daec"),
                            CategoriaId = 2,
                            Descricao = "Coxinha deliciosa e crocante.",
                            FotoUrl = "/Imagens/Salgados/coxinha_de_frango.jpg",
                            Nome = "Coxinha de Frango",
                            Preco = 3.00m,
                            QuantidadeEmEstoque = 70
                        },
                        new
                        {
                            Id = new Guid("e1795112-d1c6-4957-8f51-e00fcc81bb60"),
                            CategoriaId = 3,
                            Descricao = "Bolo de cenoura macio coberto com ganache de chocolate.",
                            FotoUrl = "/Imagens/Doces/bolo_cenoura.jpg",
                            Nome = "Bolo de Cenoura com Chocolate",
                            Preco = 6.50m,
                            QuantidadeEmEstoque = 30
                        },
                        new
                        {
                            Id = new Guid("406f24e0-4768-452a-83f9-e88910d06591"),
                            CategoriaId = 3,
                            Descricao = "Torta cremosa de limão com uma base crocante.",
                            FotoUrl = "/Imagens/Doces/torta_limao.jpg",
                            Nome = "Torta de Limão",
                            Preco = 7.00m,
                            QuantidadeEmEstoque = 40
                        },
                        new
                        {
                            Id = new Guid("78f24136-996f-4a3b-9623-cc68948e2915"),
                            CategoriaId = 4,
                            Descricao = "Sanduíche fresco com frango grelhado e cream cheese.",
                            FotoUrl = "/Imagens/Lanches/sanduiche_frango.jpg",
                            Nome = "Sanduíche de Frango com Cream Cheese",
                            Preco = 8.00m,
                            QuantidadeEmEstoque = 50
                        },
                        new
                        {
                            Id = new Guid("ddbf3619-8281-40f3-bb7c-d08f1ea25816"),
                            CategoriaId = 4,
                            Descricao = "Baguete recheada com presunto, queijo e vegetais frescos.",
                            FotoUrl = "/Imagens/Lanches/baguete.jpg",
                            Nome = "Baguete de Presunto e Queijo",
                            Preco = 7.50m,
                            QuantidadeEmEstoque = 40
                        });
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("619adf24-e943-4f2a-8f89-c942d8fc53dd"),
                            NomeUsuario = "Macoratti"
                        },
                        new
                        {
                            Id = new Guid("8278e20b-e3e6-4926-bc26-ca54112b4645"),
                            NomeUsuario = "Janice"
                        });
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.CarrinhoItem", b =>
                {
                    b.HasOne("LojaSonhoDeCafe.Entities.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojaSonhoDeCafe.Entities.Produto", "Produto")
                        .WithMany("Itens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Produto", b =>
                {
                    b.HasOne("LojaSonhoDeCafe.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Usuario", b =>
                {
                    b.HasOne("LojaSonhoDeCafe.Entities.Carrinho", "Carrinho")
                        .WithMany()
                        .HasForeignKey("CarrinhoId");

                    b.Navigation("Carrinho");
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("LojaSonhoDeCafe.Entities.Produto", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
